# configs/full.yaml
mode: A2
m: 3
d: 128
epsilon_j: [0.1, 0.2, 0.3]
nu: 0.02
gamma: 1.0
lambda: 1.0
kappa: 0.5
windows_T: [32, 64]
harmful_prompts_path: data/harmful_prompts/list.txt   # placeholder file
paraphrases_K: 5
